/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReportesRouteImport } from './routes/reportes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventarioRouteImport } from './routes/inventario'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as CotizacionesRouteImport } from './routes/cotizaciones'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventosIndexRouteImport } from './routes/eventos.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as EventosNuevoRouteImport } from './routes/eventos.nuevo'
import { Route as AdminTenantsRouteImport } from './routes/admin.tenants'
import { Route as AdminTenantsIndexRouteImport } from './routes/admin.tenants.index'
import { Route as AdminTenantsNuevoRouteImport } from './routes/admin.tenants.nuevo'
import { Route as AdminTenantsIdRouteImport } from './routes/admin.tenants.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesRoute = ReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioRoute = InventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const CotizacionesRoute = CotizacionesRouteImport.update({
  id: '/cotizaciones',
  path: '/cotizaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosIndexRoute = EventosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventosRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const EventosNuevoRoute = EventosNuevoRouteImport.update({
  id: '/nuevo',
  path: '/nuevo',
  getParentRoute: () => EventosRoute,
} as any)
const AdminTenantsRoute = AdminTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTenantsIndexRoute = AdminTenantsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminTenantsRoute,
} as any)
const AdminTenantsNuevoRoute = AdminTenantsNuevoRouteImport.update({
  id: '/nuevo',
  path: '/nuevo',
  getParentRoute: () => AdminTenantsRoute,
} as any)
const AdminTenantsIdRoute = AdminTenantsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminTenantsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/calendario': typeof CalendarioRoute
  '/catalogo': typeof CatalogoRoute
  '/clientes': typeof ClientesRoute
  '/cotizaciones': typeof CotizacionesRoute
  '/eventos': typeof EventosRouteWithChildren
  '/inventario': typeof InventarioRoute
  '/login': typeof LoginRoute
  '/reportes': typeof ReportesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/tenants': typeof AdminTenantsRouteWithChildren
  '/eventos/nuevo': typeof EventosNuevoRoute
  '/admin/': typeof AdminIndexRoute
  '/eventos/': typeof EventosIndexRoute
  '/admin/tenants/$id': typeof AdminTenantsIdRoute
  '/admin/tenants/nuevo': typeof AdminTenantsNuevoRoute
  '/admin/tenants/': typeof AdminTenantsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/catalogo': typeof CatalogoRoute
  '/clientes': typeof ClientesRoute
  '/cotizaciones': typeof CotizacionesRoute
  '/inventario': typeof InventarioRoute
  '/login': typeof LoginRoute
  '/reportes': typeof ReportesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/eventos/nuevo': typeof EventosNuevoRoute
  '/admin': typeof AdminIndexRoute
  '/eventos': typeof EventosIndexRoute
  '/admin/tenants/$id': typeof AdminTenantsIdRoute
  '/admin/tenants/nuevo': typeof AdminTenantsNuevoRoute
  '/admin/tenants': typeof AdminTenantsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/calendario': typeof CalendarioRoute
  '/catalogo': typeof CatalogoRoute
  '/clientes': typeof ClientesRoute
  '/cotizaciones': typeof CotizacionesRoute
  '/eventos': typeof EventosRouteWithChildren
  '/inventario': typeof InventarioRoute
  '/login': typeof LoginRoute
  '/reportes': typeof ReportesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/tenants': typeof AdminTenantsRouteWithChildren
  '/eventos/nuevo': typeof EventosNuevoRoute
  '/admin/': typeof AdminIndexRoute
  '/eventos/': typeof EventosIndexRoute
  '/admin/tenants/$id': typeof AdminTenantsIdRoute
  '/admin/tenants/nuevo': typeof AdminTenantsNuevoRoute
  '/admin/tenants/': typeof AdminTenantsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/calendario'
    | '/catalogo'
    | '/clientes'
    | '/cotizaciones'
    | '/eventos'
    | '/inventario'
    | '/login'
    | '/reportes'
    | '/sitemap.xml'
    | '/admin/tenants'
    | '/eventos/nuevo'
    | '/admin/'
    | '/eventos/'
    | '/admin/tenants/$id'
    | '/admin/tenants/nuevo'
    | '/admin/tenants/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendario'
    | '/catalogo'
    | '/clientes'
    | '/cotizaciones'
    | '/inventario'
    | '/login'
    | '/reportes'
    | '/sitemap.xml'
    | '/eventos/nuevo'
    | '/admin'
    | '/eventos'
    | '/admin/tenants/$id'
    | '/admin/tenants/nuevo'
    | '/admin/tenants'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/calendario'
    | '/catalogo'
    | '/clientes'
    | '/cotizaciones'
    | '/eventos'
    | '/inventario'
    | '/login'
    | '/reportes'
    | '/sitemap.xml'
    | '/admin/tenants'
    | '/eventos/nuevo'
    | '/admin/'
    | '/eventos/'
    | '/admin/tenants/$id'
    | '/admin/tenants/nuevo'
    | '/admin/tenants/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CalendarioRoute: typeof CalendarioRoute
  CatalogoRoute: typeof CatalogoRoute
  ClientesRoute: typeof ClientesRoute
  CotizacionesRoute: typeof CotizacionesRoute
  EventosRoute: typeof EventosRouteWithChildren
  InventarioRoute: typeof InventarioRoute
  LoginRoute: typeof LoginRoute
  ReportesRoute: typeof ReportesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes': {
      id: '/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof ReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario': {
      id: '/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof InventarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cotizaciones': {
      id: '/cotizaciones'
      path: '/cotizaciones'
      fullPath: '/cotizaciones'
      preLoaderRoute: typeof CotizacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos/': {
      id: '/eventos/'
      path: '/'
      fullPath: '/eventos/'
      preLoaderRoute: typeof EventosIndexRouteImport
      parentRoute: typeof EventosRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/eventos/nuevo': {
      id: '/eventos/nuevo'
      path: '/nuevo'
      fullPath: '/eventos/nuevo'
      preLoaderRoute: typeof EventosNuevoRouteImport
      parentRoute: typeof EventosRoute
    }
    '/admin/tenants': {
      id: '/admin/tenants'
      path: '/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AdminTenantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tenants/': {
      id: '/admin/tenants/'
      path: '/'
      fullPath: '/admin/tenants/'
      preLoaderRoute: typeof AdminTenantsIndexRouteImport
      parentRoute: typeof AdminTenantsRoute
    }
    '/admin/tenants/nuevo': {
      id: '/admin/tenants/nuevo'
      path: '/nuevo'
      fullPath: '/admin/tenants/nuevo'
      preLoaderRoute: typeof AdminTenantsNuevoRouteImport
      parentRoute: typeof AdminTenantsRoute
    }
    '/admin/tenants/$id': {
      id: '/admin/tenants/$id'
      path: '/$id'
      fullPath: '/admin/tenants/$id'
      preLoaderRoute: typeof AdminTenantsIdRouteImport
      parentRoute: typeof AdminTenantsRoute
    }
  }
}

interface AdminTenantsRouteChildren {
  AdminTenantsIdRoute: typeof AdminTenantsIdRoute
  AdminTenantsNuevoRoute: typeof AdminTenantsNuevoRoute
  AdminTenantsIndexRoute: typeof AdminTenantsIndexRoute
}

const AdminTenantsRouteChildren: AdminTenantsRouteChildren = {
  AdminTenantsIdRoute: AdminTenantsIdRoute,
  AdminTenantsNuevoRoute: AdminTenantsNuevoRoute,
  AdminTenantsIndexRoute: AdminTenantsIndexRoute,
}

const AdminTenantsRouteWithChildren = AdminTenantsRoute._addFileChildren(
  AdminTenantsRouteChildren,
)

interface AdminRouteChildren {
  AdminTenantsRoute: typeof AdminTenantsRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminTenantsRoute: AdminTenantsRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EventosRouteChildren {
  EventosNuevoRoute: typeof EventosNuevoRoute
  EventosIndexRoute: typeof EventosIndexRoute
}

const EventosRouteChildren: EventosRouteChildren = {
  EventosNuevoRoute: EventosNuevoRoute,
  EventosIndexRoute: EventosIndexRoute,
}

const EventosRouteWithChildren =
  EventosRoute._addFileChildren(EventosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CalendarioRoute: CalendarioRoute,
  CatalogoRoute: CatalogoRoute,
  ClientesRoute: ClientesRoute,
  CotizacionesRoute: CotizacionesRoute,
  EventosRoute: EventosRouteWithChildren,
  InventarioRoute: InventarioRoute,
  LoginRoute: LoginRoute,
  ReportesRoute: ReportesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
